services:
- id: agent-designer-1
  type: agent_designer
  url: http://localhost:8001
  health_check: /health
  weight: 1
- id: workflow-engine-1
  type: workflow_engine
  url: http://localhost:8003
  health_check: /health
  weight: 1
- id: integration-hub-1
  type: integration_hub
  url: http://localhost:8004
  health_check: /health
  weight: 1
- id: ai-model-service-1
  type: ai_model_service
  url: http://localhost:8005
  health_check: /health
  weight: 1
- id: auth-service-1
  type: auth_service
  url: http://localhost:8006
  health_check: /health
  weight: 1
- id: websocket-service-1
  type: websocket_service
  url: http://localhost:8007
  health_check: /health
  weight: 1
- id: transaction-service-1
  type: transaction_service
  url: http://localhost:8008
  health_check: /health
  weight: 1
- id: legacy-api-1
  type: legacy_api
  url: http://localhost:8002
  health_check: /health
  weight: 1
routes:
- path: ^/api/v1/agents
  service: agent_designer
  methods:
  - GET
  - POST
  - PUT
  - DELETE
  auth_required: true
  rate_limit: 100
  cache_ttl: 0
  timeout: 30
  retry_count: 3
- path: ^/api/v1/workflows
  service: workflow_engine
  methods:
  - GET
  - POST
  - PUT
  - DELETE
  auth_required: true
  rate_limit: 50
  cache_ttl: 0
  timeout: 60
  retry_count: 2
- path: ^/api/v1/integrations
  service: integration_hub
  methods:
  - GET
  - POST
  - PUT
  - DELETE
  auth_required: true
  rate_limit: 200
  cache_ttl: 300
  timeout: 30
  retry_count: 3
- path: ^/api/v1/inference
  service: ai_model_service
  methods:
  - GET
  - POST
  auth_required: true
  rate_limit: 30
  cache_ttl: 0
  timeout: 120
  retry_count: 2
- path: ^/api/v1/models
  service: ai_model_service
  methods:
  - GET
  auth_required: true
  rate_limit: 100
  cache_ttl: 3600
  timeout: 10
  retry_count: 3
- path: ^/api/v1/auth
  service: auth_service
  methods:
  - GET
  - POST
  - PUT
  - DELETE
  auth_required: false
  rate_limit: 50
  cache_ttl: 0
  timeout: 30
  retry_count: 2
- path: ^/api/v1/broadcast
  service: websocket_service
  methods:
  - POST
  auth_required: true
  rate_limit: 100
  cache_ttl: 0
  timeout: 10
  retry_count: 1
- path: ^/api/v1/transactions
  service: transaction_service
  methods:
  - GET
  - POST
  auth_required: true
  rate_limit: 50
  cache_ttl: 0
  timeout: 300
  retry_count: 1
- path: ^/api/legacy
  service: legacy_api
  methods:
  - GET
  - POST
  - PUT
  - DELETE
  auth_required: false
  rate_limit: 200
  cache_ttl: 0
  timeout: 30
  retry_count: 3
global:
  cors:
    origins:
    - '*'
    methods:
    - '*'
    headers:
    - '*'
  rate_limit:
    default: 100
    window: 60
  circuit_breaker:
    threshold: 5
    timeout: 60