volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  influxdb_data:
    driver: local
  influxdb_config:
    driver: local
  grafana_data:
    driver: local
  prometheus_data:
    driver: local
  app_logs:
    driver: local
  agent_configs:
    driver: local
  model_storage:
    driver: local
  backup_storage:
    driver: local
  rabbitmq_data:
    driver: local
  elasticsearch_data:
    driver: local
  alertmanager_data:
    driver: local