secrets:
  postgres_password:
    external: true
  redis_password:
    external: true
  jwt_secret:
    external: true
  rabbitmq_password:
    external: true
  influxdb_token:
    external: true
  grafana_password:
    external: true