global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'agent-api'
    static_configs:
      - targets: ['api:8001']
    metrics_path: '/metrics'

  - job_name: 'agent-dashboard'
    static_configs:
      - targets: ['dashboard:8051']
    metrics_path: '/metrics'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: '/metrics'

  - job_name: 'agent-services'
    static_configs:
      - targets: ['agents:8002']
    metrics_path: '/metrics'

  - job_name: 'rl-orchestrator'
    static_configs:
      - targets: ['rl-orchestrator:8003']
    metrics_path: '/metrics'